# Generated by Django 4.2.1 on 2023-06-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('type', models.CharField(choices=[('L-l', 'Local-liquor'), ('F-l', 'Foreign-liquor'), ('D', 'Drink')], max_length=50)),
                ('quantity', models.CharField(blank=True, choices=[('90ml', '90ml'), ('175ml', '175ml'), ('350ml', '350ml'), ('700ml', '700ml'), ('1l', '1l')], max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_condition', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
